/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package UI;

import Utils.ExportEx;
import DAO.LoaiGiamGiaDAO;
import Entity.LoaiGiamGia;
import Utils.Auth;
import Utils.MsgBox;
import Utils.XDate;
import java.awt.Color;
import java.io.File;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

public class GiamGiaJDiaLog extends javax.swing.JDialog {

    /**
     * Creates new form GiamGiaJDiaLog
     */
    public GiamGiaJDiaLog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    public com.k33ptoo.components.KButton getBtnAdd() {
		return btnAdd;
	}

	public void setBtnAdd(com.k33ptoo.components.KButton btnAdd) {
		this.btnAdd = btnAdd;
	}

	public com.k33ptoo.components.KButton getBtnDelete() {
		return btnDelete;
	}

	public void setBtnDelete(com.k33ptoo.components.KButton btnDelete) {
		this.btnDelete = btnDelete;
	}

	public com.k33ptoo.components.KButton getBtnUpdate() {
		return btnUpdate;
	}

	public void setBtnUpdate(com.k33ptoo.components.KButton btnUpdate) {
		this.btnUpdate = btnUpdate;
	}

	public com.github.lgooddatepicker.components.DatePicker getTxtEndDay() {
		return txtEndDay;
	}

	public void setTxtEndDay(com.github.lgooddatepicker.components.DatePicker txtEndDay) {
		this.txtEndDay = txtEndDay;
	}

	public javax.swing.JTextField getTxtNameVoucher() {
		return txtNameVoucher;
	}

	public void setTxtNameVoucher(javax.swing.JTextField txtNameVoucher) {
		this.txtNameVoucher = txtNameVoucher;
	}

	public com.github.lgooddatepicker.components.DatePicker getTxtStartDay() {
		return txtStartDay;
	}

	public void setTxtStartDay(com.github.lgooddatepicker.components.DatePicker txtStartDay) {
		this.txtStartDay = txtStartDay;
	}

	public javax.swing.JTextField getTxtValue() {
		return txtValue;
	}

	public void setTxtValue(javax.swing.JTextField txtValue) {
		this.txtValue = txtValue;
	}

	public javax.swing.JTextField getTxtVoucher() {
		return txtVoucher;
	}

	public void setTxtVoucher(javax.swing.JTextField txtVoucher) {
		this.txtVoucher = txtVoucher;
	}

	/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        kGradientPanel4 = new com.k33ptoo.components.KGradientPanel();
        kGradientPanel5 = new com.k33ptoo.components.KGradientPanel();
        jLabel2 = new javax.swing.JLabel();
        txtVoucher = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNameVoucher = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtStartDay = new com.github.lgooddatepicker.components.DatePicker();
        jLabel4 = new javax.swing.JLabel();
        txtEndDay = new com.github.lgooddatepicker.components.DatePicker();
        jLabel6 = new javax.swing.JLabel();
        txtValue = new javax.swing.JTextField();
        btnDelete = new com.k33ptoo.components.KButton();
        btnUpdate = new com.k33ptoo.components.KButton();
        btnAdd = new com.k33ptoo.components.KButton();
        lblTitle1 = new javax.swing.JLabel();
        btnNew = new com.k33ptoo.components.KButton();
        kGradientPanel6 = new com.k33ptoo.components.KGradientPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTable = new javax.swing.JTable();
        btnEnd = new com.k33ptoo.components.KButton();
        btnFirst = new com.k33ptoo.components.KButton();
        btnNext = new com.k33ptoo.components.KButton();
        btnPrev = new com.k33ptoo.components.KButton();
        btnExport = new com.k33ptoo.components.KButton();
        kGradientPanel3 = new com.k33ptoo.components.KGradientPanel();
        lblMain = new javax.swing.JLabel();
        lblProduct = new javax.swing.JLabel();
        lblBill = new javax.swing.JLabel();
        lblRevenue = new javax.swing.JLabel();
        lblStaff = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        lblInfor = new javax.swing.JLabel();
        lblHelp = new javax.swing.JLabel();
        kGradientPanel2 = new com.k33ptoo.components.KGradientPanel();
        lblTitle = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1493, 773));

        kGradientPanel1.setkEndColor(new Color(81,246,155,200));
        kGradientPanel1.setkStartColor(new Color(222,244,222,200));

        kGradientPanel4.setkEndColor(new Color(81,246,155,200));
        kGradientPanel4.setkStartColor(new Color(222,244,222,200));

        kGradientPanel5.setkEndColor(new Color(255,255,255,200));
        kGradientPanel5.setkStartColor(new Color(222,244,222,200));

        jLabel2.setText("Mã giảm giá");
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtVoucher.setPreferredSize(new java.awt.Dimension(64, 35));

        jLabel3.setText("Tên chương trình");
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel5.setText("Ngày bắt đầu");
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel4.setText("Ngày kết thúc");
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel6.setText("Giá trị");
        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnDelete.setText("Xóa");
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDelete.setkBackGroundColor(new java.awt.Color(0, 153, 153));
        btnDelete.setkEndColor(new java.awt.Color(0, 153, 153));
        btnDelete.setkHoverEndColor(new java.awt.Color(0, 153, 153));
        btnDelete.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnDelete.setkHoverStartColor(new java.awt.Color(0, 153, 153));
        btnDelete.setkSelectedColor(new java.awt.Color(0, 153, 153));
        btnDelete.setMaximumSize(new java.awt.Dimension(100, 100));
        btnDelete.setMinimumSize(new java.awt.Dimension(100, 100));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setText("Sửa");
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdate.setkBackGroundColor(new java.awt.Color(0, 153, 153));
        btnUpdate.setkEndColor(new java.awt.Color(0, 153, 153));
        btnUpdate.setkHoverEndColor(new java.awt.Color(0, 153, 153));
        btnUpdate.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnUpdate.setkHoverStartColor(new java.awt.Color(0, 153, 153));
        btnUpdate.setkSelectedColor(new java.awt.Color(0, 153, 153));
        btnUpdate.setMaximumSize(new java.awt.Dimension(100, 100));
        btnUpdate.setMinimumSize(new java.awt.Dimension(100, 100));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnAdd.setText("Thêm");
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdd.setkBackGroundColor(new java.awt.Color(0, 153, 153));
        btnAdd.setkEndColor(new java.awt.Color(0, 153, 153));
        btnAdd.setkHoverEndColor(new java.awt.Color(0, 153, 153));
        btnAdd.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnAdd.setkHoverStartColor(new java.awt.Color(0, 153, 153));
        btnAdd.setkSelectedColor(new java.awt.Color(0, 153, 153));
        btnAdd.setMaximumSize(new java.awt.Dimension(100, 100));
        btnAdd.setMinimumSize(new java.awt.Dimension(100, 100));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        lblTitle1.setText("GIẢM GIÁ");
        lblTitle1.setFont(new java.awt.Font("sansserif", 1, 26)); // NOI18N
        lblTitle1.setForeground(new Color(10,140,23,200));

        btnNew.setText("Mới");
        btnNew.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNew.setkBackGroundColor(new java.awt.Color(0, 153, 153));
        btnNew.setkEndColor(new java.awt.Color(0, 153, 153));
        btnNew.setkHoverEndColor(new java.awt.Color(0, 153, 153));
        btnNew.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnNew.setkHoverStartColor(new java.awt.Color(0, 153, 153));
        btnNew.setkSelectedColor(new java.awt.Color(0, 153, 153));
        btnNew.setMaximumSize(new java.awt.Dimension(100, 100));
        btnNew.setMinimumSize(new java.awt.Dimension(100, 100));
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel5Layout = new javax.swing.GroupLayout(kGradientPanel5);
        kGradientPanel5.setLayout(kGradientPanel5Layout);
        kGradientPanel5Layout.setHorizontalGroup(
            kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel5Layout.createSequentialGroup()
                .addGroup(kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel5Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, kGradientPanel5Layout.createSequentialGroup()
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                                .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNameVoucher, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStartDay, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtEndDay, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtValue, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtVoucher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(kGradientPanel5Layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(lblTitle1)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        kGradientPanel5Layout.setVerticalGroup(
            kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel5Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblTitle1)
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addGap(20, 20, 20)
                .addComponent(txtVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addGap(20, 20, 20)
                .addComponent(txtNameVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addGap(20, 20, 20)
                .addComponent(txtStartDay, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addGap(20, 20, 20)
                .addComponent(txtEndDay, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel6)
                .addGap(20, 20, 20)
                .addComponent(txtValue, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        kGradientPanel6.setkEndColor(new Color(255,255,255,200));
        kGradientPanel6.setkStartColor(new Color(222,244,222,200));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        tblTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã giảm giá", "Tên chương trình", "Ngày bắt đầu", "Ngày kết thúc", "Giá trị"
            }
        ));
        tblTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTable);

        btnEnd.setText(">|");
        btnEnd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEnd.setkBackGroundColor(new java.awt.Color(0, 153, 153));
        btnEnd.setkEndColor(new java.awt.Color(0, 153, 153));
        btnEnd.setkHoverEndColor(new java.awt.Color(0, 153, 153));
        btnEnd.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnEnd.setkHoverStartColor(new java.awt.Color(0, 153, 153));
        btnEnd.setkSelectedColor(new java.awt.Color(0, 153, 153));
        btnEnd.setMaximumSize(new java.awt.Dimension(100, 100));
        btnEnd.setMinimumSize(new java.awt.Dimension(100, 100));
        btnEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEndActionPerformed(evt);
            }
        });

        btnFirst.setText("|<");
        btnFirst.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnFirst.setkBackGroundColor(new java.awt.Color(0, 153, 153));
        btnFirst.setkEndColor(new java.awt.Color(0, 153, 153));
        btnFirst.setkHoverEndColor(new java.awt.Color(0, 153, 153));
        btnFirst.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnFirst.setkHoverStartColor(new java.awt.Color(0, 153, 153));
        btnFirst.setkSelectedColor(new java.awt.Color(0, 153, 153));
        btnFirst.setMaximumSize(new java.awt.Dimension(100, 100));
        btnFirst.setMinimumSize(new java.awt.Dimension(100, 100));
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        btnNext.setText(">>");
        btnNext.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNext.setkBackGroundColor(new java.awt.Color(0, 153, 153));
        btnNext.setkEndColor(new java.awt.Color(0, 153, 153));
        btnNext.setkHoverEndColor(new java.awt.Color(0, 153, 153));
        btnNext.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnNext.setkHoverStartColor(new java.awt.Color(0, 153, 153));
        btnNext.setkSelectedColor(new java.awt.Color(0, 153, 153));
        btnNext.setMaximumSize(new java.awt.Dimension(100, 100));
        btnNext.setMinimumSize(new java.awt.Dimension(100, 100));
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnPrev.setText("<<");
        btnPrev.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPrev.setkBackGroundColor(new java.awt.Color(0, 153, 153));
        btnPrev.setkEndColor(new java.awt.Color(0, 153, 153));
        btnPrev.setkHoverEndColor(new java.awt.Color(0, 153, 153));
        btnPrev.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnPrev.setkHoverStartColor(new java.awt.Color(0, 153, 153));
        btnPrev.setkSelectedColor(new java.awt.Color(0, 153, 153));
        btnPrev.setMaximumSize(new java.awt.Dimension(100, 100));
        btnPrev.setMinimumSize(new java.awt.Dimension(100, 100));
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });

        btnExport.setText("Xuất file Excel");
        btnExport.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnExport.setkBackGroundColor(new java.awt.Color(0, 153, 153));
        btnExport.setkEndColor(new java.awt.Color(0, 153, 153));
        btnExport.setkHoverEndColor(new java.awt.Color(0, 153, 153));
        btnExport.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnExport.setkHoverStartColor(new java.awt.Color(0, 153, 153));
        btnExport.setkSelectedColor(new java.awt.Color(0, 153, 153));
        btnExport.setMaximumSize(new java.awt.Dimension(100, 100));
        btnExport.setMinimumSize(new java.awt.Dimension(100, 100));
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel6Layout = new javax.swing.GroupLayout(kGradientPanel6);
        kGradientPanel6.setLayout(kGradientPanel6Layout);
        kGradientPanel6Layout.setHorizontalGroup(
            kGradientPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(kGradientPanel6Layout.createSequentialGroup()
                        .addComponent(btnFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btnEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExport, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        kGradientPanel6Layout.setVerticalGroup(
            kGradientPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExport, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout kGradientPanel4Layout = new javax.swing.GroupLayout(kGradientPanel4);
        kGradientPanel4.setLayout(kGradientPanel4Layout);
        kGradientPanel4Layout.setHorizontalGroup(
            kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kGradientPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kGradientPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        kGradientPanel4Layout.setVerticalGroup(
            kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(kGradientPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kGradientPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        kGradientPanel3.setkEndColor(new Color(222,244,222,200));
        kGradientPanel3.setkStartColor(new Color(255,255,255,200));

        lblMain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/home.png"))); // NOI18N
        lblMain.setText("Trang chủ");
        lblMain.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lblMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMainMouseClicked(evt);
            }
        });

        lblProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/gift.png"))); // NOI18N
        lblProduct.setText("Sản phẩm");
        lblProduct.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N

        lblBill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/bill.png"))); // NOI18N
        lblBill.setText("Hóa đơn");
        lblBill.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N

        lblRevenue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/earning.png"))); // NOI18N
        lblRevenue.setText("Doanh Thu");
        lblRevenue.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N

        lblStaff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/people.png"))); // NOI18N
        lblStaff.setText("Nhân viên");
        lblStaff.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/discount.png"))); // NOI18N
        jLabel1.setText("Giảm giá");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel1.setForeground(new Color(0,140,23,200));

        lblInfor.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lblInfor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/light-bulb.png"))); // NOI18N
        lblInfor.setText("Giới thiệu");
        lblInfor.setMaximumSize(new java.awt.Dimension(104, 28));
        lblInfor.setMinimumSize(new java.awt.Dimension(104, 28));
        lblInfor.setPreferredSize(new java.awt.Dimension(104, 28));

        lblHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/question.png"))); // NOI18N
        lblHelp.setText("Trợ giúp");
        lblHelp.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lblHelp.setRequestFocusEnabled(false);

        javax.swing.GroupLayout kGradientPanel3Layout = new javax.swing.GroupLayout(kGradientPanel3);
        kGradientPanel3.setLayout(kGradientPanel3Layout);
        kGradientPanel3Layout.setHorizontalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInfor, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                        .addComponent(lblMain)
                        .addComponent(lblStaff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblRevenue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblBill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        kGradientPanel3Layout.setVerticalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblMain)
                .addGap(50, 50, 50)
                .addComponent(lblProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(lblBill)
                .addGap(50, 50, 50)
                .addComponent(lblRevenue)
                .addGap(50, 50, 50)
                .addComponent(lblStaff)
                .addGap(50, 50, 50)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lblInfor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lblHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        kGradientPanel2.setkEndColor(new Color(255,255,255,200));
        kGradientPanel2.setkStartColor(new Color(222,244,222,200));

        lblTitle.setText("QUẢN LÝ CỬA HÀNG YUMFOOD");
        lblTitle.setFont(new java.awt.Font("sansserif", 1, 26)); // NOI18N
        lblTitle.setForeground(new Color(10,140,23,200));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/store.png"))); // NOI18N

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(lblLogo)
                .addGap(472, 472, 472)
                .addComponent(lblTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle)
                    .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kGradientPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kGradientPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addComponent(kGradientPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kGradientPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kGradientPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        Remove();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        Update();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        Add();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
        clearForm();
    }//GEN-LAST:event_btnNewActionPerformed

    private void tblTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTableMouseClicked
        // TODO add your handling code here:
        clicked();
    }//GEN-LAST:event_tblTableMouseClicked

    private void btnEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEndActionPerformed
        // TODO add your handling code here:\
        Last();
    }//GEN-LAST:event_btnEndActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        // TODO add your handling code here:
        First();
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        Next();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        // TODO add your handling code here:
        Prev();
    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        // TODO add your handling code here:
        exporttEx();
    }//GEN-LAST:event_btnExportActionPerformed

    private void lblMainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMainMouseClicked
        // TODO add your handling code here:
        open_Trangchu();
    }//GEN-LAST:event_lblMainMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiamGiaJDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiamGiaJDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiamGiaJDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiamGiaJDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GiamGiaJDiaLog dialog = new GiamGiaJDiaLog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton btnAdd;
    private com.k33ptoo.components.KButton btnDelete;
    private com.k33ptoo.components.KButton btnEnd;
    private com.k33ptoo.components.KButton btnExport;
    private com.k33ptoo.components.KButton btnFirst;
    private com.k33ptoo.components.KButton btnNew;
    private com.k33ptoo.components.KButton btnNext;
    private com.k33ptoo.components.KButton btnPrev;
    private com.k33ptoo.components.KButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel2;
    private com.k33ptoo.components.KGradientPanel kGradientPanel3;
    private com.k33ptoo.components.KGradientPanel kGradientPanel4;
    private com.k33ptoo.components.KGradientPanel kGradientPanel5;
    private com.k33ptoo.components.KGradientPanel kGradientPanel6;
    private javax.swing.JLabel lblBill;
    private javax.swing.JLabel lblHelp;
    private javax.swing.JLabel lblInfor;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMain;
    private javax.swing.JLabel lblProduct;
    private javax.swing.JLabel lblRevenue;
    private javax.swing.JLabel lblStaff;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JTable tblTable;
    private com.github.lgooddatepicker.components.DatePicker txtEndDay;
    private javax.swing.JTextField txtNameVoucher;
    private com.github.lgooddatepicker.components.DatePicker txtStartDay;
    private javax.swing.JTextField txtValue;
    private javax.swing.JTextField txtVoucher;
    // End of variables declaration//GEN-END:variables
    LoaiGiamGiaDAO LGG_DAO = new LoaiGiamGiaDAO();
    int index = -1;

    public void init() {
        setLocationRelativeTo(null);
        fillToTable();

    }

    public void fillToTable() {
        System.out.println("FillToTable");
        DefaultTableModel model = (DefaultTableModel) tblTable.getModel();
        model.setRowCount(0);
        List<LoaiGiamGia> list = LGG_DAO.selectAll();

        for (LoaiGiamGia loai : list) {
            model.addRow(new Object[]{loai.getMaGG(), loai.getTenCT(), loai.getNgayBD(), loai.getNgayKT(), loai.getGiaTri() + "%"});
        }
        tblTable.setModel(model);
    }

    public void setForm(LoaiGiamGia loai) {
        txtVoucher.setText(loai.getMaGG());
        txtNameVoucher.setText(loai.getTenCT());
        if (loai.getNgayBD() == null && loai.getNgayKT() == null) {
            txtStartDay.setDate(null);
            txtEndDay.setDate(null);
        } else {
            txtStartDay.setDate(new java.sql.Date(loai.getNgayBD().getTime()).toLocalDate());
            txtEndDay.setDate(new java.sql.Date(loai.getNgayKT().getTime()).toLocalDate());
        }
        txtValue.setText(String.valueOf(loai.getGiaTri()));
    }

    public LoaiGiamGia getForm() {
        LoaiGiamGia loai = new LoaiGiamGia();
        loai.setMaGG(txtVoucher.getText());
        loai.setTenCT(txtNameVoucher.getText());
        loai.setNgayBD(XDate.toDate(XDate.toString(java.sql.Date.valueOf(txtStartDay.getDate()), "dd-MM-yyyy"), "dd-MM-yyyy"));
        loai.setNgayKT(XDate.toDate(XDate.toString(java.sql.Date.valueOf(txtEndDay.getDate()), "dd-MM-yyyy"), "dd-MM-yyyy"));
        loai.setGiaTri(Integer.parseInt(txtValue.getText()));
        return loai;
    }

    public void clicked() {
        index = tblTable.getSelectedRow();
        String maGG = (String) tblTable.getValueAt(index, 0);
        LoaiGiamGia list = LGG_DAO.SelectByID(maGG);
        setForm(list);
        txtVoucher.setEnabled(false);
        btnAdd.setEnabled(false);
    }

    public void clearForm() {
        setForm(new LoaiGiamGia());
        btnAdd.setEnabled(true);
    }

    public void Add() {
        if (Validate()) {
            LoaiGiamGia loai = getForm();
            try {

                LGG_DAO.insert(loai);
                fillToTable();
                clearForm();
                MsgBox.alert(this, "Thêm thành công !!");

            } catch (Exception e) {
                System.out.println("ERROR: ADD");
                MsgBox.alert(this, "Thêm thất bại !!");
                e.printStackTrace();
            }
        }
    }

    public void Remove() {
        if (txtVoucher.getText().isEmpty()) {
            MsgBox.alert(this, "Vui lòng nhập Mã Giảm Giá");
            return;
        }
        String maGG = txtVoucher.getText();
        try {
            LGG_DAO.delete(maGG);
            fillToTable();
            clearForm();
            MsgBox.alert(this, "Xóa thành công !!");
        } catch (Exception e) {
            System.out.println("ERROR: DELETE");
            e.printStackTrace();
            MsgBox.alert(this, "Xóa thất bại !!");
        }
    }

    public void Update() {
        if (Validate()) {
            LoaiGiamGia loai = getForm();
            try {
                LGG_DAO.update(loai);
                fillToTable();
                clearForm();
                MsgBox.alert(this, "Cập nhật thành công");
            } catch (Exception e) {
                System.out.println("ERROR: UPDATE");
                e.printStackTrace();
                MsgBox.alert(this, "Cập nhật thất bại");
            }
        }
    }

    public void edit() {
        String maGG = String.valueOf(tblTable.getValueAt(index, 0));
        LoaiGiamGia loai = LGG_DAO.SelectByID(maGG);
        setForm(loai);
    }

    public void First() {
        index = 0;
        tblTable.setRowSelectionInterval(index, index);
        edit();
    }

    public void Prev() {
        index = tblTable.getSelectedRow();
        if (index > 0) {
            index--;
            tblTable.setRowSelectionInterval(index, index);
            edit();
        }
    }

    public void Next() {
        index = tblTable.getSelectedRow();
        if (index < tblTable.getRowCount() - 1) {
            index++;
            tblTable.setRowSelectionInterval(index, index);
            edit();
        }
    }

    public void Last() {
        index = tblTable.getRowCount() - 1;
        tblTable.setRowSelectionInterval(index, index);
        edit();
    }

    public void exporttEx() {
        Map<String, Object[]> studentData = new HashMap<>();
        studentData.put(
                "1",
                new Object[]{"Mã giảm giá", "Tên chương trình", "Ngày bất đầu", "Ngày kết thúc", "Giá trị"
                }
        );
        List<LoaiGiamGia> list = LGG_DAO.selectAll();
        for (int i = 0; i < list.size(); i++) {
            studentData.put(
                    // STT của hàng (i)
                    String.valueOf(i + 2),
                    // nội dung
                    new Object[]{list.get(i).getMaGG(),
                        list.get(i).getTenCT(),
                        list.get(i).getNgayBD(),
                        list.get(i).getNgayKT(),
                        list.get(i).getGiaTri(),}
            );
        }
        File path = new File("D:\\FPT Polytechnic\\Fall2023\\PRO1041 - DuAn1\\DanhSachGiamGia");
        ExportEx.exportExcel(studentData, path, "Giảm giá");
        MsgBox.alert(this, "Xuất file thành công !!");
    }

    public boolean Validate() {
        if (txtVoucher.getText().isEmpty()) {
            MsgBox.alert(this, "Vui lòng kiểm tra lại Mã Giảm Giá");
            return false;
        } else if (txtVoucher.getText().isEmpty()) {
            MsgBox.alert(this, "Vui lòng kiểm tra lại Tên Chương Trình");
            return false;
        } else if (txtStartDay.getText().isEmpty()) {
            MsgBox.alert(this, "Vui lòng kiểm tra lại Ngày Kết Thúc");
            return false;
        } else if (txtEndDay.getText().isEmpty()) {
            MsgBox.alert(this, "Vui lòng kiểm tra lại Ngày Kết Thúc");
            return false;
        } else if (!txtValue.getText().matches("(?=.*[0-9])[0-9]+")) {
            MsgBox.alert(this, "Vui lòng kiểm tra lại Giá trị");
            return false;
        }
        return true;
    }
    
    private void open_Trangchu(){
        this.dispose();
        new Main3(new JFrame(), true).setVisible(true);
    }
    private void open_SanPham(){
        this.dispose();
        new SanPhamJDiaLog(new JFrame(), true).setVisible(true);
    }
    private void open_NhanVien(){
        this.dispose();
        new NhanVienJDialog(new JFrame(),true).setVisible(true);
    }
    private void open_HoaDon(){
        this.dispose();
        new HoaDonJDiaLog(new JFrame(), true).setVisible(true);
    }
    private void open_TroGiup(){
        
    }
    private void open_DoanhThu(){
        this.dispose();
        new DoanhThuJDiaLog(new JFrame(), true).setVisible(true);
    }
    private void DangXuat(){
        this.dispose();
        Auth.clear();
        new DangNhapJDiaLog(new JFrame(), true).setVisible(true);
    }
    private void open_GioiThieu(){
        
    }
}
